@extends('layouts.fullwith')
@section('content')
  <div class="col-md-12">
                 <div class="shadow-box">
                    <!-- <div class="pageobject" data-top="-198px" data-left="150px" data-zindex="1000">
                         <img src="./assets/images/content/kid2.png" alt="">
                     </div>-->
                     <h4 class="color-motive uppercase pull-left">Therapies4Kids</h4>
                     @include('includes.socialBar')
                     <div class="clearfix"></div>
                     <hr>
                     <h3 class="color-motive">The Pedia Suit Protocol™</h3>

                     <strong>Solving Sensory Deficits</strong>

                     <p><strong>Movement disorders, suit therapy and intensive integrated programs</strong></p>
                     <p>Children with autism spectrum disorder (ASD) often have significant problems related to sensory processing and sensorimotor deficits, even when their primary diagnosis is not sensory integration dysfunction (SID). Children with SID have difficulty registering or organizing and using the sensory information from their body and from the environment. When this process is disordered, problems in learning, development or behavior may become evident. Frequently, they show motor impairments, including poor muscle contraction around joints, low muscle tone, and decreased balance and equilibrium skills. Children with sensorimotor dysfunction typically have problems in accurately producing a movement or controlling the execution of a movement. Sensory processing, motor planning and motor performance delays are seen in young children with SID and ASD.</p>
                     <p>Another group of developmental disabilities that involve more chronic movement disorders is cerebral palsy (CP). CP is a term used to describe a category of disorders that impair the control of movement and that appear in the first few years of life. It is a condition caused by injury to parts of the brain responsible for proper muscles and body control. The causes of CP include illness during pregnancy, premature delivery, or lack of oxygen supply to the baby. It may also occur early in life as a result of an accident, lead poisoning, viral infection, child abuse or other factors. According to Ketelaar et al (2001), “no evidence exist that brain damage can be reversed, however, maturational and adaptive process may change the clinical picture of the child overtime”.</p>
                     <p>Chief among the causes of CP is an insufficient amount of oxygen or poor flow of blood reaching the fetal or newborn brain. This can occur by premature separation of the placenta, an awkward birth position, interference with the umbilical cord, or labor that goes on too long or is too abrupt. Other factors may be associated with premature birth, RH or A-B-O blood type incompatibility between parents, infection of the mother with German measles or other viral diseases in early pregnancy, and microorganisms that attack the newborn’s central nervous system. A less common type is acquired CP, of which head injury is the most frequent cause, usually the result of motor vehicle accidents, falls, or child abuse. CP by definition is neither progressive nor communicable and the intensity of CP may range from mild to moderate or severe.</p>
                     <p>CP is classified according to the type of movement disorder and which limb or limbs are affected. The four broad categories include spastic, athetoid, ataxic, and mixed forms. In the spastic form, the patient exhibits upper motor neuron signs, such as weakness, hypertonicity, hyperreflexia, clonus, pathologic reflexes and a tendency to contractures. This type is further classified as to the limb impairment and includes quadriplegia (the symmetric impairment of all four extremities), diplegia (in which the bilateral spasticity of the legs is greater than that of the arms), monoplegia (a rare type in which only one limb is involved), paraplegia (involving only the lower extremities) and triplegia (another rare type, with only one unaffected limb). The athetoid category (also called dyskinetic CP) includes uncontrolled, slow, writhing movements. These movements may affect the hands, feet, arms or legs and, in some cases, the face and tongue, which may also affect speech, causing dysarthria. The ataxic category is a rare form, affecting the sense of balance and depth perception. Lastly, is the mixed forms category, where it is common for patients to have symptoms of more than one of the three previous forms. The most common mixed form includes spasticity and athetoid movements (National Institute of Neurological Disorders and Stroke (NINDS, 2008).</p>
                     <p>Doctors diagnose CP by testing motor skills and reflexes, looking into medical history, and employing a variety of specialized tests. Infants with CP are frequently slow to reach developmental milestones such as learning to roll over, sit, crawl, or walk. Some patients suffering from CP may also experience impairments beyond the neuromuscular involvement, such as mental impairment, seizures, visual and auditory dysfunction, growth problems, and abnormal sensation and perception. Symptoms of CP may include difficulty with fine motor tasks (e.g. writing or using scissors), difficulty maintaining balance or walking, and involuntary movements. The orthopedic difficulties encountered in children with CP are frequently a result of high muscle tone, spasticity, and rigidity that prevent normal growth of muscle and cause contractures.</p>
                     <p>There is no standard therapy that works for all CP patients. Patients with CP may need different kinds of therapy to overcome their impairments. Treatment for CP focuses on how to help the child maximize his or her potential (Ketelaar et al, 2001). The treatment plan may include physical therapy, which helps to develop the strength of muscles, as well as, improve or develop skills to enhance their independence in motor skills such as walking, sitting, self-care, play and maintaining balance. The intervention plan may also include occupational therapy, which helps to develop fine motor skills such as dressing, feeding, writing, and other daily living tasks. These therapies are focused on decreasing the degree of impairment (e.g., muscle spasticity) and increasing participation in activities of daily living (United Cerebral Palsy (UCP), 2003). Speech therapy may help patients to develop communication skills focusing in particular on speaking, which may be difficult due to problems with muscle tone of the tongue and throat. Still others may need surgery, drug therapy (e.g., to control seizures and muscle spasms) and/or mechanical aids that are tailored to the unique needs and impairments of each patient.</p>
                     <p>Rehabilitation center Therapies 4 Kids in Fort Lauderdale, Florida offers an intense and complex therapy program adjusted to the needs of particular patients with neurological disorders (e.g., ASD,CP, TBI, down syndrome) or developmental delays. This includes, when appropriate, suit therapy and intensive integrated physical therapy.</p>
                     <p>PediaSuit™ therapy has been proposed as an alternative to conventional physiotherapy and is based on a suit originally designed by the Russians for use by cosmonauts in space to minimize the effects of weightlessness. Suit therapy or Dynamic Proprioceptive Correction (DPC), has been popularized as a treatment modality in Poland and the United States, and is focused on improving sensory stimulation and providing patients with the ability to stand and move through suit therapy resistance. This method allows a person to learn movement, standing posture and balance strategies.</p>
                     <p>PediaSuit™ consists of a cap, vest, shorts, knee pads and specially adapted shoes with hooks and elastic cords that help tell the body how it is supposed to move in space. Therapists use the PediaSuit™ to hold the body in proper physical alignment. It serves as an exo-skeleton that produces a vertically directed load of approximately thirthy-three to eighty-eight pounds. The suit increases the ability of the patient to develop new motor plans. With the ability to provide artificial formation and reinforcement of appropriate movement habits with repetitive exercises, patient learn new motor plans and built strength at the same time.</p>
                     <p>PediaSuit™ therapy increases deep proprioceptive awareness and positions the child in a more ideal alignment during various activities. Re-establishing the correct postural alignment plays a crucial role in normalizing muscle tone, sensory and vestibular function. The suit aligns the body as close to normal as possible and the idea is to move body parts against resistance, thus improving muscle strength. An attached series of elastic cords provides compression to the body’s joints (tactile stimulation) and resistance to muscles when movement occurs. Through placement of the elastic cords, selected muscle groups can be exercised as the patient moves limbs, thus, suit therapy is a form of controlled exercise against a resistance. It is also claimed that the suit improves endurance, flexibility, balance, coordination, improves bone density, improves body and spatial awareness.</p>
                     <p>Intensive integrated physical therapy programs are customized to fit the needs of each child, with specific functional goals and usually involve a rehabilitation program that includes about 200 minutes of exercise per day for 6 days a week, including 90 to 120 minutes of the suit application. PediaSuit™ therapy is often used as part of a comprehensive program of intensive physiotherapy of five to seven hours a day for four weeks (UCP, 2003). It combines the best elements of various techniques and methods, and has a sound rationale based on physiology of exercises. It is important to note that use of the suit is only one component of an overall approach. Parental involvement is highly encouraged and parents are often part of the treatment program. It needs to be mentioned, however, that a true intensive therapy program is not merely doing the same exercise over and over again, but rather is a structured approach to physical activity with consideration to person’s individual cycles of progressive overload, fatigue and recovery. You can find this type of therapy at www.therapies4kids.com</p>
                     <p>The key element in an intensive plan is a strengthening and balance program established for the participant based on his/her individual needs, strengths and weaknesses. Increased strength is reflected in daily functional activities that usually follow or are combined with strengthening exercises. Elimination of pathological reflexes and establishing new, correct, and functional patterns of movements is of significant importance. A typical day of an intensive program may consists of warming up and deep tissue massage, tone reduction and sensory integration techniques, decreasing pathological movement patterns, increasing active proper movement patterns, stretching/strengthening specific muscle groups responsible for functional movement, progressive resistance exercise, balance/coordination and endurance training, and transferring of functional activities and gait training. Thus, intensive therapy is ideal for those looking to accelerate their progress in developmental and functional skills.</p>
                     <p>The Ability Exercise Unit (AEU) is also sometimes used to assist children in functional activities along with strengthening exercises. The AEU is utilized to isolate and strengthen particular muscles or muscle groups to help gain muscle strength, flexibility, range of motion, as well as functional skills. Children sometimes refer to the AEU as the “monkey cage”. In the “spider cage” the children are hooked up a belt around their waist that is attached to the cage using bungee cords. Just enough assistance is given using the bungee cords to allow the child the security and balance needed to practice activities on their own. The cage also allows the child and therapist to work on activities that would normally take two or three therapists to work on, by acting as extra hands. Children are able to accomplish activities in the spider cage that they are not able to do without the assistance of the bungee cords. Depending on the way the bungee cords are placed, one can practice sitting, kneeling, quadruped, standing, strengthening exercises and many other activities.</p>
                     <p>Children’s physical development and movement is linked closely to other aspects of their daily learning. It is influenced by their growing confidence and enjoyment of physical play, by their increasing ability to control their own bodies through movement and by their physical well-being and strength. As children develop physically, they become faster, stronger, more mobile and more secure of their balance, and they start to use these skills in a wider range of physical activities and also begin to become more aware of themselves as individuals. This developing sense of identity is linked closely to their own self image, self-esteem and confidence.</p>
                     <p>For more information please call <strong>954-491-6611</strong> or visit their websites: www.therapies4kids.com and <a href="http://www.pediasuit.com" target="_blank">www.pediasuit.com</a></p>
                     <p>References:</p>
                     <p>1. National Institute of Neurological Disorders and Stroke (NINDS). Bethesda, MD, 2008. <a href="http://www.ninds.nih.gov/disorders/cerebral_palsy/detail_cerebral_palsy.htm" target="_blank">http://www.ninds.nih.gov/disorders/cerebral_palsy/detail_cerebral_palsy.htm</a><br />
                     2. The Treatment of Cerebral Palsy. Washington, DC: United Cerebral Palsy (UCP) Research &amp; Educational Foundation; 2003en<br />
                     3. Ketelaar, M., Vermeer, A., Hart, H., Beek, E., Helders, P. Effects of a functional therapy program on motor abilities of children with cerebral palsy. Physical Therapy, V.81, number 9, September 2001.</p>
                     <p><strong>Lodging &amp; Transportation</strong></p>
                     <p>SunDeck Hotel, located directly across the street from us is offering for the months of September / October rates of $45.00 per nigbt + taxes to any and all Therapies 4 Kids / PediaSuit clients. Visit their Website: <a href="http://www.sundeckmotel.com" target="_blank">www.sundeckmotel.com</a> and tell them you are with Therapies 4 Kids or PediaSuit</p>
                     <p>Therapies 4 Kids, Inc. can help to arrange housing at the local Ronald McDonald House while your child is enrolled in our program. They request a $15.00 per night donation. This donation is not mandatory and no family is turned away for their inability to pay. Other arrangements are available with local hotels and apartment houses at pre-arranged pricing.</p>
                     <p>TRANSPORTATION IS AVAILABLE TO AND FROM AIRPORTS ON REQUEST. Call us for more information: <strong>1-954-491-6611</strong></p>
                     <p><strong>Payment and Reservations</strong></p>
                     <p>Therapies 4 Kids are providers for:</p>
                     <p>1. Blue Cross / Blue Shield Of Florida<br />
                     2. Tri-Care Standard Plan<br />
                     3. Aetna &#8211; PPO<br />
                     4. Beechstreet<br />
                     5. United Healthcare PPO</p>
                     <p>In order to reserve a session spot we encourage you to call as soon as possible at <strong>954-491-6611</strong> &#8211; after hours at 954-608-9930. Space is very limited and the only way to ensure your reservation is to place a US $1000.00 deposit with Therapies 4 Kids, Inc. We accept personal checks, wires or major credit cards for payment. The remaining balance of payment is due 4 weeks after the deposit or 4 weeks prior to arrival. Should you decide to pay online here just click the deposit or balance links and your payment will be secure.</p>
                     <p>Once you decide to enroll your child into our intensive fitness program please print out the below medical clearance form and take it to your child&#8217;s pediatrician or neurologist to sign. Please fax this signed form to <strong>954-241-6726</strong>.</p>
                     <p><span style="text-decoration: underline;">Cancellation/Refund Policy</span></p>
                     <p>If you need to cancel your reservation for an intensive fitness session for any reason, the money you paid will be credited to your account. Your credit will be honored for up to one full year from the date the reservation was canceled. Should you choose to reschedule, you can apply your credit towards another session within one year from the date of cancellation. Unfortunately, cancellations and refunds are only accepted for the reasons stated below and the amount paid will be refunded withing 90 days less 10% for Administrative fees if:</p>
                     <p>1. Child does not meet OUR Doctor&#8217;s criteria to participate in our intensive program.<br />
                     2. OUR Physician will not authorize participation in the program due to a extreme medical condition which does not enable the child to do Physical therapy or treatment of any kind.</p>
                     <p><span style="text-decoration: underline;">Patient Sick Policy</span></p>
                     <p>Due to the fragile nature of our patients, please be courteous and do NOT bring your child to therapy if they have any of the following:</p>
                     <p>1. Any fever (99 and above)<br />
                     2. Green or yellow runny nose<br />
                     3. Vomiting or diarrhea due to illness<br />
                     4. Any change in skin color or texture<br />
                     5. Breathing difficulty<br />
                     6. &gt;Coughing fits/ coughing up mucous<br />
                     7. Any infectious illness such as a rash, impetigo, pink eye, chicken pox, etc.<br />
                     8. Ring worm<br />
                     9. Other</p>
                     <p>If your child becomes ill during the treatment session, we will discuss this with the parent/guardian and the child will need to be seen by a physician. If there is an emergency situation, Therapies 4 Kids, Inc. staff will call 911 and we will contact the parent/guardian if they are not present.</p>
                     <p>If the child comes to therapy with any infectious illness, it is up to the clinician&#8217;s discretion to cancel the treatment. If your child misses therapy due to illness and is enrolled in the intense program, we will attempt to make up the time.</p>
                     <p>Your child is very important to us and we want to ensure that they will get the most out of their therapy sessions. But, pushing an ill child to continue therapy will not benefit the child.</p>
                     <p><strong> ? MEDICAL CLEARANCE FORM </a></strong></p>
                     <p><strong> ?  WIRE INFORMATION </a></strong></p>


                 </div>
             </div>
@stop