@extends('layouts.fullwith')
@section('content')
  <div class="col-md-12">
                 <div class="shadow-box">
                    <!-- <div class="pageobject" data-top="-198px" data-left="150px" data-zindex="1000">
                         <img src="./assets/images/content/kid2.png" alt="">
                     </div>-->
                     <h4 class="color-motive uppercase pull-left">Therapies4Kids</h4>
                     @include('includes.socialBar')
                     <div class="clearfix"></div>
                     <hr>
                     <h3 class="color-motive">Developmental Milestones</h3>
                        <p><span style="text-decoration: underline;">Birth</span> &#8211; Physiological Flexion, Full head lag with pull to sit, clears nose from the bed on stomach, Pelvis high with legs flexed, head sags forward in supported sitting, hands fisted yet easily opened</p>
                        <p><span style="text-decoration: underline;">Possible Red Flags</span> &#8211; absence of isolated finger movement; head always positioned to one side; inability to clear face in prone position; exaggerated back extensor arching</p>
                        <p><span style="text-decoration: underline;">1 month</span> &#8211; Moves both arms and legs while on stomach; alternately kicks legs while on back; able to briefly align head with trunk in supported sitting; opens and closes hands; reaching efforts depend on body position and are linked with visual gaze on an object</p>
                        <p><span style="text-decoration: underline;">Possible Red Flags</span> &#8211; difficulty flexing legs under body; limited arcs of extremity movement; absence of reciprocal leg movements; no evidence of grasp and release</p>
                        <p><span style="text-decoration: underline;">2 to 3 months</span> &#8211; Arms more extended; lateral weight shifting; rolls to back from the belly; alternately kicking legs while on back; midline head alignment; minimal head lag during pull-to-sit; propped sitting may be emerging; reaches and grasps with eye-hand coordination; finger play in mouth; may achieve a 25-30 degree arc through pivot-prone rotation; rolls from side to back</p>
                        <p><span style="text-decoration: underline;">Possible Red Flags (2 to 3 months)</span> &#8211; Inability to right head at end of pull-to-sit maneuver; arching of back</p>
                        <p><span style="text-decoration: underline;">4 to 5 months</span> &#8211; props on elbows with elbows in line with the shoulders ; will weight shift to free arm and reach with one hand while on belly; will pivot while on stomach; begins to push back up onto hands and knees; will alternate feet to mouth and bridging while on back; will also attempt to roll to side with leg or arm leading while on back; ring sit emerging; attempts lateral weight-shift to support the body with one arm and grasp a toy with the other while in sitting; arms are extended fully up in supine to reach in midline; palmar grasp on cube; holds toy with two hands; pivot-prone rotation; may attempt rocking in quadruped and pushing backwards</p>
                        <p><span style="text-decoration: underline;">Possible Red Flags (4 to 5 months)</span>- Lateral weight-shifting difficult in prone; unable to extend arms fully and toward midline in supine; kyphotic sitting position; unable to sit erect even with support</p>
                        <p><span style="text-decoration: underline;">6 to 7 month</span>s &#8211; Plays with feet while on back, Tucks chin and pulls to sit, reaches with bilateral arms, pushes up on extended arms while on stomach, sits independently with hands propped forward, stands with support at hands, rocks on hands and knees, transitions from all fours to sitting, rapid rolling, able to static sit and play with a toy, crawls on belly</p>
                        <p><span style="text-decoration: underline;">Possible Red Flags (6 to 7 months)</span> &#8211; inability to achieve midline head position in supine or sitting; no evidence of movement in prone; inability to tilt pelvis to bring thighs to hands</p>
                        <p><span style="text-decoration: underline;">8 to 9 months</span> &#8211; Refuses to lie on back; raises self to sit; assumes all fours easily and rocks readily, transitions in and out of sitting to quadruped or prone; manipulates toy in sitting position; anterior and lateral protective reactions present; controlled release; transfers objects; radial digital grasp; crawls/creeps; pulls to stand with support</p>
                        <p><span style="text-decoration: underline;">Possible Red Flags (8 to 9 months)</span> &#8211; commando crawl or bunny hop; w-sit as the only sitting position</p>
                        <p><span style="text-decoration: underline;">10 to 11 months </span>- Creeps/crawls very quickly; pulls to stand by rolling up over feet; pulls to stand through half kneeling; bounces in standing ;transitions to sitting and quadruped; rotates or pivots while sitting to reach; transitions to prone or supine easily; pincer grasp present; sidesteps or cruises with external support; walks with one hand held; lowers to sit on the floor</p>
                        <p><span style="text-decoration: underline;">Possible Red Flags (10 to 11 months)</span> &#8211; inability to transition among sitting positions; pulls to stand using arms only; inability to stand on flat feet</p>
                        <p><span style="text-decoration: underline;">12 months</span> &#8211; stands up through quadruped; moves rapidly into sitting or quadruped to standing; wide variety of sitting positions includes side sitting; rolls a ball; scoops with a spoon finger feeds; independent walking with high guard arms and wide support base; lowers self with control from standing; may begin to move in and out of a full squat position</p>
                        <p><span style="text-decoration: underline;">Possible Red Flags (12 months)</span> &#8211; trunk and extremity stiffness; laxity or instability; poor coordination may prevent hands-knees locomotion and emergence of standing</p>
                        <p><span style="text-decoration: underline;">13 to 15 months</span> &#8211; Sustained standing without external support; stoops to pick up object and regains standing; stands from the floor without support; holds two cubes in same hand; builds 2-3 cube tower; hurls objects to the floor from table or high chair; flings ball with elbow extension; independent walking; climbs into adult chairs; walks backward a few steps; stoops and recovers easily; carries object while walking; creeps up steps or walks up with external support</p>
                        <p><span style="text-decoration: underline;">Possible Red Flags (13 to 15 months)</span> – Moves around environment using bottom scooting, bunny-hop, or rolling</p>
                        <p><span style="text-decoration: underline;">15 to 18 months</span> &#8211; Carries or pulls an object while walking; creeps down steps; steps on ball positioned for kicking; tries climbing steps using the railing; turns book pages several at a time; scribbles; builds tower with 3-4 cubes; takes pegs from board attempts to replace; base of support almost equal to width of pelvis; running not well coordinated or with arm reciprocation; walks to the side a few steps</p>
                        <p><span style="text-decoration: underline;">Possible Red Flags (15 to 18 months)</span> – Lacks independent upright walking</p>
                        <p><span style="text-decoration: underline;">18 to 24 months</span> &#8211; Stands on one foot momentarily; steps over low barrier; builds 5-6 cube tower; places pellet in bottle; separates pop beads; imitates motor activities; walks up steps with step-to-pattern and external one-hand support; running speed and fluidity increasing; tries to jump off bottom step</p>
                        <p><span style="text-decoration: underline;">Possible Red Flags (18 to 24 months)</span> – base of support wider or narrower than pelvis; falls often while walking or running</p>
                        <p><span style="text-decoration: underline;">2 years</span> &#8211; Kicks small ball forward; throws ball overhead; jumps off low step; builds 6-7 cube tower; turns book pages singly; turns doorknobs; ascends and descends stairs alone with step-to-pattern; attempts foot-over-foot with adult support</p>
                        <p><span style="text-decoration: underline;">Possible Red Flags (2 years)</span> – Not walking or falls often while walking; in-toeing or excessive external rotation; avoids arts and crafts projects; base of support much wider than pelvis or narrowed</p>
                        <p><span style="text-decoration: underline;">2 1/2 years</span> &#8211; Jumps off step with 1 foot leading; jumps off floor with 2 feet; can imitate walking on tiptoes; mounts tricycle; imitates straight, horizontal, and circular strokes with marker; tripod grip emerging; running well-coordinated with arm reciprocation; walks on line backward</p>
                        <p><span style="text-decoration: underline;">Possible Red Flags (2- 3 1/2 years)</span> – Not walking or falls often while walking; in-toeing or excessive external rotation; avoids arts and crafts projects; base of support much wider than pelvis or narrowed</p>
                        <p><span style="text-decoration: underline;">3 years</span> &#8211; Jumps off step and lands with 2 feet; easily propels riding vehicle with feet on floor, may pedal; jumps over 1-2 inch object; positions arms in anticipation to catch ball; imitates cross-stroke with marker; attempts scissor cut; imitates block bridge building; hand preference emerging; walks up steps reciprocally; running with speed and fluidity; jumps off bottom step</p>
                        <p><span style="text-decoration: underline;">Possible Red Flags (2- 3 1/2 years)</span> – Not walking or falls often while walking; in-toeing or excessive external rotation; avoids arts and crafts projects; base of support much wider than pelvis or narrowed</p>
                        <p><span style="text-decoration: underline;">3 1/2 years</span> &#8211; Mounts, pedals and dismounts several types of 3-wheel riding vehicles; stands on 1 foot for &gt;3 seconds; hops on 1 foot; kicks ball; may jump forward several times in succession; strings and unstrings beads based on size; builds bridges using blocks; removes bottle cap to check contents; runs up to a ball to kick it; may jump with 2 feet in succession</p>
                        <p><span style="text-decoration: underline;">Possible Red Flags (3 1/2 years)</span> – Response times insufficient to succeed at catching a ball or soft object; unable to maintain single leg stability to kick, hop, or stand on one leg</p>
                        <p><span style="text-decoration: underline;">4 years</span> &#8211; Rotation of body follows forward projection of ball; several hops in succession on 1 foot; stands and walks on tiptoes; rides 2 wheeled bike with training wheels; dynamic tripod pencil grip; makes cross stroke; attempts to trace ling; hand preference is established; running fluid with arm reciprocation</p>
                        <p><span style="text-decoration: underline;">Possible Red Flags (4 years)</span> – Does not attempt skills requiring moderate to maximal balance challenges such as climbing and jumping off heights; catching and kicking balls is difficult; ambiguous hand preference</p>
                        <p><span style="text-decoration: underline;">4 1/2 years</span> &#8211; Catches ball by preparing arm as ball approaches, elbows may be at the sides; throws ball to another person 8-10 feet away; jumps 2 – 3 inches off the floor; folds sheet of paper in half; cuts large square from paper sheet; beginning to form letters; walks on curb or beam without falling</p>
                        <p><span style="text-decoration: underline;">Possible Red Flags (4 1/2 years)</span> – Difficulty with skills requiring asymmetric body positioning or disassociated extremity movements, such as throwing with one arm, jumping on one leg</p>
                        <p><span style="text-decoration: underline;">5 years</span> &#8211; Jumps forward and sideways with 2-foot landing emerging; jumps over objects 6-8 inches from the floor; throws ball to hit target at 10 feet; roller skates; rides a bike; dynamic tripod grip; draws simple shapes, letters or numbers; places small pegs in pegboard and removes them easily; winds string on spool; broad jumps; drop kicks; jumps rope</p>
                        <p><span style="text-decoration: underline;">Possible Red Flags (5 years)</span> – Difficulty mounting or pedaling any ride on toy; often cannot imitate a motor act after seeing another child complete it; base of support wider than pelvis; cannot catch ball; fist grip rather than tripod grip of marker or pencil</p>
                 </div>
             </div>
@stop